# Generated by Django 5.1.5 on 2025-02-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
