# Generated by Django 5.1.5 on 2025-02-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_producto_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Direccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='Precio',
            new_name='precio',
        ),
    ]
